######################################################################
# Automatically generated by qmake (2.01a) ? 6? 2 14:32:54 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ../Library
INCLUDEPATH += . ../Library/include
LIBS += -lboost_filesystem-mt -lboost_system-mt -lboost_program_options-mt

unix {
    CONFIG += link_pkgconfig
    PKGCONFIG += opencv
}

# Input
SOURCES += main.cpp mainwindow.cpp
HEADERS += mainwindow.h
